### ISSUE TITLE
Support for "friskvård"

### ISSUE THREAD

**Issue by Gustavhol** [PatrikOlin/butler-burton#9]
Some way to register the above mentioned on checkout would be great. To the point of my long term usage of bb as my daily butler depending on it. 

It needs to be able to take a param of how long (number of kvartar or minutes), and what kind of absence.

**Comment by Gustavhol** [comment]
As an added bonus it would be fräckt to be able to set them without checking in or out.

**Comment by PatrikOlin** [comment]
solved in v3.0.0
